openapi: 3.0.0
info:
  description: This api to fetch crypto currency market summary
  version: "1.0.0"
  title: Crypto Currency API
servers:
  - url: /api/v1 # local/default server
paths:
  /login:
    post:
      tags:
        - "Login"
      summary: Verify login and generate auth token(jwt)
      x-openapi-router-controller: "app.login.views"
      operationId: "login"
      requestBody:
        description: Enter username and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Get auth token (jwt)
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Login"
              examples:
                marketLogin:
                  value:
                    status: success
                    detail: logged in successfully
                    status_code: 200
                    result:
                      auth_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQzOTY2MDcsInVzZXJuYW1lIjohFbFnvgKHY
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '401':
          description: Unauthorized Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '403':
          description: Forbidden Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '404':
          description: Resource Not Found
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '422':
          description: Invalid Input Payload
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
  /marketsummaries:
    get:
      summary: Return all market summaries
      x-openapi-router-controller: "app.market.views"
      operationId: "get_all_market_summaries"
      responses:
        '200':
          description: All market summaries response
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryResponse"
              examples:
                marketSummaries:
                  value:
                    status: success
                    detail: fetched all market summaries successfully
                    status_code: 200
                    result:
                      - MarketName: BTC-LTC
                        High: 0.0135
                        Low: 0.012
                        Volume: 3833.97619253
                        Last: 0.01349998
                        BaseVolume: 47.03987026
                        TimeStamp: 2014-07-09T07:22:16.72
                        Bid: 0.01271001
                        Ask: 0.012911
                        OpenBuyOrders: 45
                        OpenSellOrders: 45
                        PrevDay: 0.01229501
                        Created: 2014-02-13T00:00:00
                        DisplayMarketName: string
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '401':
          description: Unauthorized Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '403':
          description: Forbidden Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '404':
          description: Resource Not Found
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '422':
          description: Invalid Input Payload
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
      security:
        - jwt: [ 'secret' ]
  /marketsummary:
    get:
      summary: Return market summary
      x-openapi-router-controller: "app.market.views"
      operationId: "get_market_summary"
      parameters:
        - in: query
          name: market
          required: true
          schema:
            type: string
          description: Filter data using market
      responses:
        '200':
          description: Market summary response
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryResponse"
              examples:
                marketSummary:
                  value:
                    status: success
                    detail: fetched market summary successfully
                    status_code: 200
                    result:
                      - MarketName: BTC-LTC
                        High: 0.0135
                        Low: 0.012
                        Volume: 3833.97619253
                        Last: 0.01349998
                        BaseVolume: 47.03987026
                        TimeStamp: 2014-07-09T07:22:16.72
                        Bid: 0.01271001
                        Ask: 0.012911
                        OpenBuyOrders: 45
                        OpenSellOrders: 45
                        PrevDay: 0.01229501
                        Created: 2014-02-13T00:00:00
                        DisplayMarketName: string
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '401':
          description: Unauthorized Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '403':
          description: Forbidden Request
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '404':
          description: Resource Not Found
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '422':
          description: Invalid Input Payload
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/marketSummaryError"
      security:
        - jwt: ['secret']

components:
#  security token
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: app.CommonLib.security_helper.TokenOperations.decode_token
#  success result
  schemas:
    Login:
      type: object
      properties:
        status:
          type: string
        result:
          type: object
          properties:
            auth_token:
              type: string
        detail:
          type: string
        status_code:
          type: integer
    marketSummaryResponse:
      type: object
      properties:
        status:
          type: string
        result:
          $ref: "#/components/schemas/marketSummaryResult"
        detail:
          type: string
        status_code:
          type: integer
    marketSummaryError:
      type: object
      properties:
        status:
          type: string
        result:
          type: object
        detail:
          type: string
        status_code:
          type: integer
    marketSummaryResult:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              MarketName:
                type: string
              High:
                type: number
                format: float
              Low:
                type: number
                format: float
              Volume:
                type: number
                format: float
              Last:
                type: number
                format: float
              BaseVolume:
                type: number
                format: float
              TimeStamp:
                type: string
              Bid:
                type: number
                format: float
              Ask:
                type: number
                format: float
              OpenBuyOrders:
                type: integer
              OpenSellOrders:
                type: integer
              PrevDay:
                type: number
                format: float
              Created:
                type: string
              DisplayMarketName:
                type: string


